### ISSUE TITLE
Infraestructure migration to Github Actions

### ISSUE THREAD

**Issue by luiz2025flip** [luiz2025flip/pre-o-rapido#1]
Migrate repository from Lovable to GitHub.
Automate deploys via GitHub Actions.
Maintain exactly the same structure of:
- Database
- API endpoints
- App features

Database:
SQLite local (offline-first)
Schema existente:
```prisma
model PriceCache {
  id        Int    @id @default(autoincrement())
  origin    String
  destination String
  prices    Json   // { uber: 15.90, 99: 14.50 }
  expiresAt DateTime
}
```
Zero changes in tables or fields

Actions needed:
- Create `deploy.yml` file for GitHub Actions
- Configure `LOVABLE_PROJECT_ID` and `LOVABLE_TOKEN` secrets
- Ensure compatibility with Android Go

Command to execute:
```bash
npx prisma migrate deploy --preview-feature
```

Expected flow:
1.  Generate CI/CD workflow
2.  Configure environment secrets
3.  Trigger initial migration

Workflow model:
```yaml
name: Lovable Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to Lovable
        uses: lovable/deploy-action@v2
        with:
          project-id: ${{ secrets.LOVABLE_PROJECT_ID }}
          token: ${{ secrets.LOVABLE_TOKEN }}
```
